name: Deploy 

on:
  workflow_call:
    inputs:
      image-uri:
        type: string
        required: true
        description: The URI of the container image to insert into the ECS task definition
      container-name:
        type: string
        required: true
        description: The name of the container defined in the containerDefinitions section of the ECS task definition
        default: app
      service:
        type: string
        required: false
        description: The name of the ECS service to deploy to.
      services:
        type: string
        required: false
        description: The name of the ECS service to deploy to.
      cluster:
        type: string
        required: true
        description: The name of the ECS service's cluster.
      aws-region:
        required: false
        type: string
        default: eu-central-1
    
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    concurrency: deploy-${{matrix.SERVICE_NAME}}
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(inputs.services) }}
    steps:
      - name: Hello world!
        run: |
          echo "image-uri ${{ inputs.image-uri }}"
          echo "container-name ${{ inputs.container-name }}"
          echo "services ${{ inputs.services }}"
          echo "service ${{ matrix.SERVICE_NAME }}"
          echo "image-uri ${{ inputs.image-uri }}"
      # - name: Matrix
      #   strategy:
      #     matrix: ${{ fromJson(needs.calc-deps.outputs.matrix) }}