name: Build docker image and push to ECR

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      aws-account-id:
        required: true
        type: string
      aws-access-key-id:
        required: true
        type: string
      aws-secret-access-key:
        required: true
        type: string
      aws-region:
        required: true
        type: string
        default: eu-central-1

jobs:
  docker_build_push:
    name: Build docker image and push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Export short sha to outputs
        id: export-sha
        run: |
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build docker image
        run: |
          docker build \
            --build-arg COMMIT_ID=${{ steps.export-sha.outputs.sha_short }} \
            --tag ${{ inputs.aws-account-id }}.dkr.ecr.{{ inputs.aws-region }}.amazonaws.com/it3:${{ steps.export-sha.outputs.sha }} \
            --tag ${{ inputs.aws-account-id }}.dkr.ecr.{{ inputs.aws-region }}.amazonaws.com/it3:${{ steps.export-sha.outputs.sha_short }} \
            .

      - name: Push docker image to ECR
        run: |
          docker push --all-tags ${{ inputs.aws-account-id }}.dkr.ecr.{{ inputs.aws-region }}.amazonaws.com/${{ inputs.image-name}}:${{ steps.export-sha.outputs.sha_short }}
