name: Build docker image and push to ECR

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      cache-mix:
        required: false
        type: boolean
        default: false
      # cache-gems:
      #   required: false
      #   type: boolean
      #   default: false
      aws-account-id:
        required: true
        type: string
      aws-region:
        required: true
        type: string
        default: eu-central-1
    
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  docker_build_push:
    name: Build docker image and push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        if: ${{ inputs.cache-mix }}
        with:
          path: deps
          key: ${{ runner.os }}-mix-deps-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Export short sha to outputs
        id: export-sha
        run: |
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build docker image
        run: |
          docker build \
            --build-arg COMMIT_ID=${{ steps.export-sha.outputs.sha_short }} \
            --tag 123.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/it3:${{ steps.export-sha.outputs.sha }} \
            --tag 123.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/it3:${{ steps.export-sha.outputs.sha_short }} \
            .

      - name: Push docker image to ECR
        run: |
          docker push --all-tags ${{ inputs.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.image-name}}:${{ steps.export-sha.outputs.sha_short }}
